FORMAT: 1A

# Polls

Polls is a simple API allowing consumers to view polls and vote in them.

## Messages Collection [/questions]

### Retrieve Message [GET]
+ Request
    + Headers

            Authorization: Basic ABCDEF

+ Response 200 (application/json)

        {
            "message":"Hello World!"
        }

+ Request (application/json)
    + Body

            {
               "grant_type": "client_credentials"
            }

+ Response 401 (text/plain)

        There is no such a message for you, dear guest.

+ Response 410 (text/plain)

        The message you are searching for does not exist anymore.
