FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# luyan

This is a simple API allowing database administrator to backup the Oracle database instance.

## Backup Collection [/backups]

### Create a backup job [POST]

+ Request (application/json)
        
        {
            "jobName": "my job 1",
            "dbUser": "oracle",
            "dbPassword": "********",
            "dbPort": 1521,
            "serviceName": "pdb1"
        }

+ Response 202

### Retrieve backup jobs [GET]

+ Response 200 (application/json)

        [
            {
                "jobId": 1,
                "jobName": "my job 1",
                "jobStatus": "Completed"
            },
            {
                "jobId": 2,
                "jobName": "my job 2",
                "jobStatus": "In Progress"
            }
        ]